add custom fields, data type changed for fields
paskowski/movies-cms pull request #13
Opened 2020-12-16 13:26 UTC by s17534

2020-12-16 13:51 UTC, MaciejSikorski requested changes

2020-12-16 13:51 UTC, MaciejSikorski commented on features/movie/custom-fields.php
> +                    'Familijny' => 'familijny',
Jedyna duża litera!!!
Nwm czy klucze nie powinny być po angielsku, ale to do ustalenia

2020-12-16 13:51 UTC, MaciejSikorski commented on features/movie/custom-fields.php
> +                'key' => 'field_rating',
To nwm czy będzie w ten sposób rozwiązanie jeszcze nie przejrzałem możliwosci jak zaimplementować moduł oceniania

2020-12-16 13:53 UTC, paskowski commented on features/movie/custom-fields.php
> +                    'Familijny' => 'familijny',
We're going to use taxonomies to handle this bit, so I'd remove it for now. We can talk about it today.

2020-12-16 15:48 UTC, paskowski commented on features/movie/single/template.php
> +                        $post_object = get_sub_field('actor');
This is how we should be getting properties of a post that is embedded in the repeater field.
First we get actor post object from the repeater's subfield.
Then we set it to `$post` variable - naming is **important** here, it won't work if you will name this variable differently.
Then we call `setup_postdata($post)` which allows us to call methods such as  `the_title()` or `get_field('field_name')` easily.

2020-12-16 15:49 UTC, paskowski commented on features/movie/single/template.php
> +                    wp_reset_postdata();
Before closing while we have to call `wp_reset_postdata()` to tidy up everything, otherwise `$post` variable will be messed up and cause us problems.

2020-12-17 14:30 UTC, paskowski requested changes

2020-12-17 14:30 UTC, paskowski commented on features/movie/single/template.php
> +                                    <h class="card-title"><?php echo $post->post_title ; ?></h5>
There's missing 5 in the `<h5>` opening tag. Use `the_title();` instead of `echo $post->post_title;`

2020-12-17 14:30 UTC, paskowski commented on features/movie/single/template.php
> +                                <img src="<?php echo esc_url($actor_img['url']); ?>" class="card-img-top" alt="...">
Create a separate variable for this bit `esc_url($actor_img['url']);` below `$actor_img`, so you will be printing one thing instead of a method call, that will make it easier to refactor in the future.

I'd rename `$actor_img` to `$actor_field`, then extract the url to new variable called `$actor_img`.

2020-12-17 14:54 UTC, s17534 commented on features/movie/single/template.php
> +                                <img src="<?php echo esc_url($actor_img['url']); ?>" class="card-img-top" alt="...">
Done

2020-12-17 15:53 UTC, paskowski commented on features/movie/single/template.php
> +                                    <h class="card-title"><?php echo $post->post_title ; ?></h5>
@s17534

2020-12-19 07:29 UTC, paskowski approved these changes
👍

2020-12-19 08:39 UTC, MaciejSikorski approved these changes

2020-12-19 08:39 UTC, merged