Actor - Role - Movie relationship
paskowski/movies-cms pull request #17
Opened 2020-12-22 14:09 UTC by paskowski

Implemented simpler relationships between actors and their roles in movies

2020-12-22 14:14 UTC, paskowski commented on .vscode/launch.json
> +{
I debugged a lot of stuff and VSC had issues with creating proper config so I decided to add it to repo after finally getting it right

2020-12-22 14:14 UTC, paskowski commented on acf-config.php
> +function replace_repeater_field( $where ) {
This filter helps with querying data stored in repeater

2020-12-22 14:15 UTC, paskowski commented on features/actor/custom-fields.php
> -            ),
Actor will no longer keep info about movies in which he/she plays

2020-12-24 13:55 UTC, Sikora00 requested changes

2020-12-24 13:55 UTC, Sikora00 commented on features/actor/single/template.php
> +                $loop = new WP_Query($args);
Is it posible to define some function like getActorMoviesIterator($id) outside of the template?

2020-12-24 14:33 UTC, paskowski commented on features/actor/single/template.php
> +                $loop = new WP_Query($args);
I will look into that

2021-01-07 08:43 UTC, s17534 approved these changes

2021-01-07 09:49 UTC, Sikora00 approved these changes

2021-01-07 09:49 UTC, merged